### ISSUE TITLE
Check script needs ssl flag

### ISSUE THREAD

**Issue by foozmeat** [sensu-plugins/sensu-plugins-haproxy#12]
pull request incoming

**Comment by Evesy** [comment]
Hey @foozmeat 

Any chance of opening a PR against this repository for this change? I see the existing PR is just against the master branch of your forked repository & it'd be nice to get this change implemented.

Unless I'm mistaken the SSL option should be passed in as a hash too:

```res = Net::HTTP.start(config[:stats_source], config[:port], config[:use_ssl]) do |http|```

Should be:

```res = Net::HTTP.start(config[:stats_source], config[:port], use_ssl: config[:use_ssl]) do |http|```

Thanks!

**Comment by Evesy** [comment]
@majormoses @foozmeat I guess this one can be closed now?

**Comment by foozmeat** [comment]
yes that's fine. I'll switch back to your repo.
