### ISSUE TITLE
Release 2.0.3 is missing on bonsai

### ISSUE THREAD

**Issue by hyvs** [sensu-plugins/sensu-plugins-haproxy#55]
Release 2.0.3 is missing [on bonsai](https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-haproxy).

This release is important to fix compatibility with haproxy 2.4

Some maintainer can publish it ? 🙏

**Comment by jindraj** [comment]
I'm facing the same issue. Can someone please publish it? please 🙏

**Comment by hyvs** [comment]
Release 2.0.3 is available on bonsai.
